/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SkillStoreRouteImport } from './routes/skill-store'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingSkillsRouteImport } from './routes/setting/skills'
import { Route as SettingSkillLogsRouteImport } from './routes/setting/skill-logs'
import { Route as SettingProviderRouteImport } from './routes/setting/provider'
import { Route as SettingHelpRouteImport } from './routes/setting/help'
import { Route as SettingGeneralRouteImport } from './routes/setting/general'
import { Route as ChatIdRouteImport } from './routes/chat/$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillStoreRoute = SkillStoreRouteImport.update({
  id: '/skill-store',
  path: '/skill-store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingSkillsRoute = SettingSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingRoute,
} as any)
const SettingSkillLogsRoute = SettingSkillLogsRouteImport.update({
  id: '/skill-logs',
  path: '/skill-logs',
  getParentRoute: () => SettingRoute,
} as any)
const SettingProviderRoute = SettingProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingRoute,
} as any)
const SettingHelpRoute = SettingHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => SettingRoute,
} as any)
const SettingGeneralRoute = SettingGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingRoute,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/preview': typeof PreviewRoute
  '/setting': typeof SettingRouteWithChildren
  '/skill-store': typeof SkillStoreRoute
  '/skills': typeof SkillsRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
  '/setting/help': typeof SettingHelpRoute
  '/setting/provider': typeof SettingProviderRoute
  '/setting/skill-logs': typeof SettingSkillLogsRoute
  '/setting/skills': typeof SettingSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/preview': typeof PreviewRoute
  '/setting': typeof SettingRouteWithChildren
  '/skill-store': typeof SkillStoreRoute
  '/skills': typeof SkillsRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
  '/setting/help': typeof SettingHelpRoute
  '/setting/provider': typeof SettingProviderRoute
  '/setting/skill-logs': typeof SettingSkillLogsRoute
  '/setting/skills': typeof SettingSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/preview': typeof PreviewRoute
  '/setting': typeof SettingRouteWithChildren
  '/skill-store': typeof SkillStoreRoute
  '/skills': typeof SkillsRoute
  '/welcome': typeof WelcomeRoute
  '/chat/$id': typeof ChatIdRoute
  '/setting/general': typeof SettingGeneralRoute
  '/setting/help': typeof SettingHelpRoute
  '/setting/provider': typeof SettingProviderRoute
  '/setting/skill-logs': typeof SettingSkillLogsRoute
  '/setting/skills': typeof SettingSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/preview'
    | '/setting'
    | '/skill-store'
    | '/skills'
    | '/welcome'
    | '/chat/$id'
    | '/setting/general'
    | '/setting/help'
    | '/setting/provider'
    | '/setting/skill-logs'
    | '/setting/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/preview'
    | '/setting'
    | '/skill-store'
    | '/skills'
    | '/welcome'
    | '/chat/$id'
    | '/setting/general'
    | '/setting/help'
    | '/setting/provider'
    | '/setting/skill-logs'
    | '/setting/skills'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/preview'
    | '/setting'
    | '/skill-store'
    | '/skills'
    | '/welcome'
    | '/chat/$id'
    | '/setting/general'
    | '/setting/help'
    | '/setting/provider'
    | '/setting/skill-logs'
    | '/setting/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  PreviewRoute: typeof PreviewRoute
  SettingRoute: typeof SettingRouteWithChildren
  SkillStoreRoute: typeof SkillStoreRoute
  SkillsRoute: typeof SkillsRoute
  WelcomeRoute: typeof WelcomeRoute
  ChatIdRoute: typeof ChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-store': {
      id: '/skill-store'
      path: '/skill-store'
      fullPath: '/skill-store'
      preLoaderRoute: typeof SkillStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting/skills': {
      id: '/setting/skills'
      path: '/skills'
      fullPath: '/setting/skills'
      preLoaderRoute: typeof SettingSkillsRouteImport
      parentRoute: typeof SettingRoute
    }
    '/setting/skill-logs': {
      id: '/setting/skill-logs'
      path: '/skill-logs'
      fullPath: '/setting/skill-logs'
      preLoaderRoute: typeof SettingSkillLogsRouteImport
      parentRoute: typeof SettingRoute
    }
    '/setting/provider': {
      id: '/setting/provider'
      path: '/provider'
      fullPath: '/setting/provider'
      preLoaderRoute: typeof SettingProviderRouteImport
      parentRoute: typeof SettingRoute
    }
    '/setting/help': {
      id: '/setting/help'
      path: '/help'
      fullPath: '/setting/help'
      preLoaderRoute: typeof SettingHelpRouteImport
      parentRoute: typeof SettingRoute
    }
    '/setting/general': {
      id: '/setting/general'
      path: '/general'
      fullPath: '/setting/general'
      preLoaderRoute: typeof SettingGeneralRouteImport
      parentRoute: typeof SettingRoute
    }
    '/chat/$id': {
      id: '/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingRouteChildren {
  SettingGeneralRoute: typeof SettingGeneralRoute
  SettingHelpRoute: typeof SettingHelpRoute
  SettingProviderRoute: typeof SettingProviderRoute
  SettingSkillLogsRoute: typeof SettingSkillLogsRoute
  SettingSkillsRoute: typeof SettingSkillsRoute
}

const SettingRouteChildren: SettingRouteChildren = {
  SettingGeneralRoute: SettingGeneralRoute,
  SettingHelpRoute: SettingHelpRoute,
  SettingProviderRoute: SettingProviderRoute,
  SettingSkillLogsRoute: SettingSkillLogsRoute,
  SettingSkillsRoute: SettingSkillsRoute,
}

const SettingRouteWithChildren =
  SettingRoute._addFileChildren(SettingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  PreviewRoute: PreviewRoute,
  SettingRoute: SettingRouteWithChildren,
  SkillStoreRoute: SkillStoreRoute,
  SkillsRoute: SkillsRoute,
  WelcomeRoute: WelcomeRoute,
  ChatIdRoute: ChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
